### ISSUE TITLE
HTTPS support

### ISSUE THREAD

**Issue by molnarg** [xkxx/node-spdy-proxy#1]
The proxy works great, but https requests are not answered by the server. I see that there is support for HTTP CONNECT method in the code, but this codepath is not reached at all.

**Comment by xkxx** [comment]
It works for me. Can you post your proxy.conf and proxy.log here so we can have a more detailed look?

**Comment by molnarg** [comment]
Well, it's the default config. Now I realised that chrome probably doesn't trust the key I generated. It may be the root of the problem, I will check tomorrow.

**Comment by molnarg** [comment]
OK it was just a certificate error. Chrome is not very helpful when it comes to spdy error messages...
